In [1]:
import torch

## Variables
+ Tensor: input
+ Variable (parameter): autograd
+ nn.Module

In [4]:
a = torch.rand((2, 3))
a

tensor([[0.1024, 0.6080, 0.2611],
        [0.1369, 0.3111, 0.7754]])

In [5]:
# 数据类型
print(a.type())

torch.FloatTensor


In [6]:
# 存储设备
a.device

device(type='cpu')

In [7]:
# 内存的分布，稠密分布，一块连续地址
a.layout

torch.strided

In [8]:
torch.tensor([1, 2, 3], dtype=torch.float32, device='cpu')

tensor([1., 2., 3.])

In [17]:
# 稀疏张量 -> 非 0 元素的坐标
torch.sparse_coo_tensor([[0, 1, 1], [2, 0, 2]], [3, 4, 5], [4, 4])

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3, 4, 5]),
       size=(4, 4), nnz=3, layout=torch.sparse_coo)

In [18]:
torch.sparse_coo_tensor([[0, 1, 1], [2, 0, 2]], [3, 4, 5], [4, 4]).to_dense()

tensor([[0, 0, 3, 0],
        [4, 0, 5, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

## Operator

In [30]:
a = torch.tensor([1])
b = torch.tensor([2])
a + b

tensor([3])

In [31]:
a * b 

tensor([2])

In [32]:
a / b

tensor([0.5000])

In [33]:
a = torch.ones(2, 1)
b = torch.ones(1, 2)

In [35]:
a

tensor([[1.],
        [1.]])

In [36]:
b

tensor([[1., 1.]])

In [41]:
a * b

tensor([[1., 1.],
        [1., 1.]])

In [39]:
a@b

tensor([[1., 1.],
        [1., 1.]])

In [42]:
torch.mm(a, b)

tensor([[1., 1.],
        [1., 1.]])