## Convolution

In [1]:
import torch
import numpy as np
import torch.nn.functional as F

In [2]:
data = np.array(list(range(25))).reshape(5, 5) * 1.0
data

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [3]:
kernel = np.ones((3, 3))
kernel

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
data = torch.tensor(data)
data

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]], dtype=torch.float64)

In [5]:
data = torch.reshape(data, (1, 1, 5, 5))
data

tensor([[[[ 0.,  1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.,  9.],
          [10., 11., 12., 13., 14.],
          [15., 16., 17., 18., 19.],
          [20., 21., 22., 23., 24.]]]], dtype=torch.float64)

In [6]:
kernel = torch.tensor(kernel)
kernel

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
kernel = torch.reshape(kernel, (1, 1, 3, 3))
kernel

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], dtype=torch.float64)

In [8]:
output = F.conv2d(data, kernel, stride=1)
output

tensor([[[[ 54.,  63.,  72.],
          [ 99., 108., 117.],
          [144., 153., 162.]]]], dtype=torch.float64)

### Padding

In [13]:
output = F.conv2d(data, kernel, stride=1, padding=2)
output

tensor([[[[  0.,   1.,   3.,   6.,   9.,   7.,   4.],
          [  5.,  12.,  21.,  27.,  33.,  24.,  13.],
          [ 15.,  33.,  54.,  63.,  72.,  51.,  27.],
          [ 30.,  63.,  99., 108., 117.,  81.,  42.],
          [ 45.,  93., 144., 153., 162., 111.,  57.],
          [ 35.,  72., 111., 117., 123.,  84.,  43.],
          [ 20.,  41.,  63.,  66.,  69.,  47.,  24.]]]], dtype=torch.float64)

## Stride

In [14]:
output = F.conv2d(data, kernel, stride=2)
output

tensor([[[[ 54.,  72.],
          [144., 162.]]]], dtype=torch.float64)

## MaxPooling

In [12]:
output = F.max_pool2d(data, kernel_size=3)
output

tensor([[[[12.]]]], dtype=torch.float64)

In [50]:
F.max_pool2d(output, kernel_size=1)

tensor([[[[ 54.,  72.],
          [144., 162.]]]], dtype=torch.float64)

## Flatten

In [16]:
torch.flatten(output)

tensor([ 54.,  72., 144., 162.], dtype=torch.float64)