## Linear Transformation

In [1]:
import torch
import torch.nn as nn
from torch.nn import Parameter

In [2]:
linear = torch.nn.Linear(3, 2)

In [4]:
linear.weight

Parameter containing:
tensor([[-0.0185, -0.1946,  0.4488],
        [-0.1127, -0.5284,  0.3269]], requires_grad=True)

In [5]:
linear.bias

Parameter containing:
tensor([0.3131, 0.4168], requires_grad=True)

In [9]:
linear.weight = Parameter(torch.tensor([[1.0, 2.0, 3.0], [2.0, 3.0, 4.0]]))
linear.weight

Parameter containing:
tensor([[1., 2., 3.],
        [2., 3., 4.]], requires_grad=True)

In [11]:
linear.bias = Parameter(torch.tensor([1.0, 2.0]))
linear.bias

Parameter containing:
tensor([1., 2.], requires_grad=True)

In [19]:
data = torch.tensor([[1.0, 2.0, 3.0], [-2.0, 3.0, -4.0]])
data

tensor([[ 1.,  2.,  3.],
        [-2.,  3., -4.]])

In [20]:
print(linear.weight.shape)
print(data.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [21]:
y = linear(data)
y

tensor([[15., 22.],
        [-7., -9.]], grad_fn=<AddmmBackward0>)

In [22]:
relu = torch.nn.ReLU()
relu(y)

tensor([[15., 22.],
        [ 0.,  0.]], grad_fn=<ReluBackward0>)

## Pytorch multiply
+ torch.mul()，和*乘完全一样
+ torch.mm()，矩阵叉乘，即对应元素相乘相加，不支持broadcast操作
+ torch.bmm()，三维矩阵乘法，一般用于mini-batch训练中
+ torch.matmul()，叉乘，支持broadcast操作
+ https://blog.csdn.net/weixin_42065178/article/details/119517404